package com.lumen.ui.screens

import androidx.compose.runtime.staticCompositionLocalOf

private fun russianPlural(count: Int, one: String, few: String, many: String): String {
    val lastTwo = count % 100
    val last = count % 10
    return when {
        last == 1 && lastTwo != 11 -> one
        last in 2..4 && lastTwo !in 12..14 -> few
        else -> many
    }
}

class LumenStrings {
    var localeCode = "en"
    var home = ""; var servers = ""; var routing = ""; var settings = ""; var logs = ""
    var noServer = ""; var fastest = ""; var addNode = ""; var searchServers = ""
    var pingAll = ""; var pinging = ""; var importClipboard = ""; var noServers = ""
    var allGroups = ""; var manual = ""; var subscriptions = ""; var addSubscription = ""
    var refresh = ""; var delete = ""; var edit = ""; var auto = ""; var never = ""
    var nodes = ""; var updated = ""; var nameOptional = ""; var cancel = ""; var add = ""
    var splitTunneling = ""; var off = ""; var offDescription = ""; var vpnOnly = ""
    var vpnOnlyDescription = ""; var exclude = ""; var excludeDescription = ""
    var appsUsingVpn = ""; var appsBypassingVpn = ""; var searchApps = ""
    var loadingApps = ""; var hideSystem = ""; var autoSelect = ""; var clear = ""
    var vpnEngine = ""; var connection = ""; var muxDescription = ""; var muxConcurrency = ""
    var tlsFragmentation = ""; var tlsDescription = ""; var fragmentPackets = ""
    var fragmentLength = ""; var fragmentDelay = ""; var tunnelMtu = ""; var localProxy = ""
    var localInbound = ""; var localInboundDescription = ""; var allowLan = ""
    var allowLanDescription = ""; var behavior = ""; var proxyOnly = ""; var proxyOnlyDesc = ""; var autoConnect = ""
    var autoConnectDescription = ""; var language = ""; var systemDefault = ""
    var speedTest = ""; var testing = ""; var runSpeedTest = ""; var export = ""
    var noLogs = ""; var connectingStatus = ""
    var connectionError = ""; var diagnostics = ""
    var openLogs = ""; var preferIpv6 = ""; var preferIpv6Description = ""
    var blockQuic = ""; var blockQuicDescription = ""; var sniffRouteOnly = ""
    var sniffRouteOnlyDescription = ""; var socksPort = ""; var httpPort = ""
    var centerConnect = ""; var centerConnecting = ""; var centerConnected = ""; var centerError = ""
    var importFromClipboard = ""; var importQrCode = ""; var importFromFile = ""; var importManually = ""
    var refreshSubscription = ""; var deleteSubscription = ""; var autoUpdateOneHour = ""
    var expiresUnlimited = ""; var daysRemaining = ""; var serverCount = ""
    var sortByPing = ""; var pingGroup = ""; var sortBy = ""; var sortByName = ""
    var subscriptionSettings = ""; var trafficSettings = ""; var appSettings = ""
    var infoSection = ""; var version = ""; var community = ""; var back = ""
    var requestParameters = ""; var directLoad = ""; var directLoadDesc = ""
    var sendHwid = ""; var sendHwidDesc = ""; var allowOverrides = ""; var allowOverridesDesc = ""
    var subscriptionAutoUpdate = ""; var subscriptionAutoUpdateDesc = ""; var subscriptionAutoUpdateInterval = ""
    var subscriptionIncludeRegexLabel = ""; var subscriptionExcludeRegexLabel = ""
    var subscriptionUseProxyTun = ""; var subscriptionUseProxyTunDesc = ""
    var subscriptionAllowHttp = ""; var subscriptionAllowHttpDesc = ""
    var subscriptionConverter = ""; var subscriptionConverterDesc = ""; var subscriptionConverterUrlLabel = ""
    var subscriptionProfile = ""; var proxyDns = ""; var directDns = ""; var autoSelectUrl = ""
    var checkInterval = ""; var toleranceMs = ""; var appearance = ""; var theme = ""
    var domainIpRouting = ""; var appRouting = ""; var geoResourceFiles = ""
    var domainsAndIpDirect = ""; var directRulesNotice = ""; var domainsDirectLabel = ""
    var ipCidrDirectLabel = ""; var geoSourceLabel = ""; var geoNotLoaded = ""; var geoManagedByCore = ""
    var groupDefault = ""; var importAction = ""
    var themeSettings = ""; var done = ""; var greenTheme = ""; var greenThemeDesc = ""
    var dashboardStyle = ""; var dashboardStyleDefault = ""; var dashboardStyleSlider = ""; var dashboardStyleCentered = ""
    var launcherIcon = ""; var launcherIconDesc = ""; var launcherIconSystem = ""; var launcherIconLight = ""; var launcherIconDark = ""
    var deleteAllServers = ""; var deleteAllServersConfirm = ""
    var routingPresets = ""; var routingPresetsDesc = ""; var presetLan = ""; var presetAds = ""; var presetRu = ""; var presetCn = ""; var presetIr = ""; var presetGlobalProxy = ""; var customRules = ""
    var lightTheme = ""; var lightThemeDesc = ""; var darkTheme = ""; var darkThemeDesc = ""
    var additional = ""; var materialYou = ""; var materialYouDesc = ""
    var materialYouUnavailable = ""; var rosePineTheme = ""; var rosePineThemeDesc = ""
    var amoledBlack = ""; var amoledBlackDesc = ""; var connectionStyleTitle = ""
    var classicStyle = ""; var compactStyle = ""
    var addOrPaste = ""; var swipeOrTapToConnect = ""; var swipeOrTapToDisconnect = ""
    var slideToConnect = ""; var slideToDisconnect = ""; var paste = ""
    var speedLabel = "Speed"; var sessionLabel = "Session"
    var copyLink = ""; var exportQrCode = ""; var ping = ""
    var subscriptionProperties = ""; var exportAll = ""; var exportSelected = ""
    var selected = ""; var url = ""; var copied = ""; var udpPing = ""
    var address = ""; var action = ""; var directAction = ""; var proxyAction = ""
    var blockAction = ""; var noRulesYet = ""; var clearAll = ""
    var dnsSettings = ""; var dnsModeSection = ""; var dnsModeAuto = ""
    var dnsModeAndroid = ""; var dnsModeSecure = ""; var dnsModeJson = ""
    var dnsModeAutoHint = ""; var dnsModeAndroidHint = ""; var dnsModeSecureHint = ""
    var dnsModeJsonHint = ""; var dnsCustomJsonLabel = ""; var dnsDirectSection = ""; var dnsProxySection = ""
    var dnsServersLabel = ""; var dnsTypeLabel = ""; var dnsStrategyLabel = ""
    var dnsIpv4Only = ""; var dnsIpv4OnlyDesc = ""; var dnsBehaviorSection = ""
    var dnsHijack = ""; var dnsHijackDesc = ""; var dnsFakeIp = ""; var dnsFakeIpDesc = ""
    var dnsParallel = ""; var dnsParallelDesc = ""; var dnsOptimistic = ""
    var dnsOptimisticDesc = ""; var dnsGeoCheck = ""; var dnsGeoCheckDesc = ""
    var dnsHostsSection = ""; var dnsHostsLabel = ""; var dnsOverride = ""
    var dnsOverrideDesc = ""; var dnsHostname = ""; var dnsIpv4 = ""
    var vibration = ""; var vibrationDesc = ""; var showNotification = ""; var showNotificationDesc = ""; var notificationSpeed = ""; var notificationSpeedDesc = ""
    var speedStats = ""; var speedStatsDesc = ""
    // Falls back to English when a locale does not translate it.
    var autoReconnectNetwork = "Reconnect on network change"
    var autoReconnectNetworkDesc = "Rebuild the tunnel automatically when Wi-Fi and mobile data switch (all protocols)"
    var validateProxyDataPath = "Validate proxy data path"
    var validateProxyDataPathDesc = "Test HTTPS through the selected server before enabling the VPN (slower startup)"
    var copyAction = "Copy"
    var geoDownloadAction = "Download rule sets"
    var geoUpdating = "Downloading\u2026"
    var socks5Auth = "Socks5 authorization"
    var socks5AuthDesc = "Protect the local proxy from unauthorized access. The HTTP proxy becomes unavailable. Connections from the LAN are protected as well."
    var socks5Login = "Socks5 login"
    var socks5PasswordLabel = "Socks5 password"
    var socks5Reset = "Reset login/password"
    var pingSettings = ""; var pingTypeLabel = ""; var pingTimeoutLabel = ""
    var pingConcurrencyLabel = ""; var pingUrlLabel = ""; var pingAutoOnOpen = ""
    var pingAutoOnOpenDesc = ""
    var categoryAppearance = ""; var categoryConnection = ""; var categoryTunnel = ""
    var categoryProviders = ""; var categoryOther = ""; var perAppProxy = ""
    var trafficUsed = ""; var trafficTotal = ""; var expiresLabel = ""
    var updates = "Updates"; var updatesDesc = "Check Android releases on GitHub"
    var currentVersion = "Current version"; var latestVersion = "Latest Android version"
    var checkUpdates = "Check for updates"; var checkingUpdates = "Checking…"
    var updateAvailable = "A new Android version is available"
    var upToDate = "You already have the latest Android version"
    var downloadUpdate = "Download update"; var updateCheckFailed = "Could not check for updates"
    var downloadingUpdate = "Downloading update\u2026"
    var autoCheckUpdates = "Automatically check for updates"
    var autoCheckUpdatesDesc = "Check GitHub when Lumen opens, at most once a day"
    var updateInstallPermissionRequired =
        "Allow Lumen to install apps, then return to continue the update"
    var updateInstallerUnavailable = "Android's package installer is unavailable"
    var androidReleaseTag = "Android release tag"
    var unlimited = ""; var subscriptionInfo = ""; var password = ""
    var editNode = ""; var close = ""; var nodeName = ""; var protocolField = ""
    var transportLabel = ""; var pathLabel = ""; var hostHeaderLabel = ""; var grpcServiceNameLabel = ""
    var securityLabel = ""; var sniLabel = ""; var alpnLabel = ""; var utlsFingerprintLabel = ""
    var certificateSha256Label = ""
    var allowInsecureTlsLabel = ""; var realityPublicKeyLabel = ""; var realityShortIdLabel = ""
    var uuidLabel = ""; var flowLabel = ""; var noneOption = ""; var encryptionMethodLabel = ""
    var passwordAuthLabel = ""; var obfsLabel = ""; var obfsPasswordLabel = ""; var uuidPasswordLabel = ""
    var congestionControlLabel = ""; var userPasswordOptionalLabel = ""; var privateKeyLabel = ""
    var peerPublicKeyLabel = ""; var wgAddressLabel = ""; var presharedKeyLabel = ""
    var allowedIpsLabel = ""; var reservedLabel = ""; var awgJunkParamsLabel = ""
    var amneziaCompatible = ""; var amneziaCompatibleDesc = ""
    // Falls back to English when a locale does not translate it.
    var disableAmnezia = "Disable Amnezia compatibility"
    var disableAmneziaDesc = "Remove the junk parameters and use the server as plain WireGuard"
    var useProxyLabel = "Use proxy"
    var proxyServerLabel = "Proxy server"
    var proxyUsernameLabel = "Proxy username (optional)"
    var proxyPasswordLabel = "Proxy password (optional)"
    var obfsProxyHint = "obfsproxy runs inside Lumen, no extra binary is needed"
    var masqueProfileIdLabel = "Profile ID"
    var masqueAuthTokenLabel = "Auth token"
    var wgMtuLabel = "MTU (optional)"
    var wgDnsLabel = "DNS servers (comma separated)"
    var wgKeepaliveLabel = "Persistent keepalive, s"
    var awgHeadersLabel = "AmneziaWG magic headers"
    var telemetryEnabled = "Send anonymous diagnostics"
    var telemetryEnabledDesc = "Share the app version and anonymous error statistics to help fix problems"
    var openvpnConfigLabel = ""; var autoNodeDescriptionLabel = ""; var serverLabel = ""
    var portLabel = ""; var saveAction = ""
    // Ping & speed screen. Falls back to English when a locale does not translate it.
    var pingAttemptsLabel = "Attempts per server"
    var pingAggregateLabel = "Result from attempts"
    var pingRetryDelayLabel = "Delay between attempts (ms)"
    var pingThresholds = "Latency colors"
    var pingGoodLabel = "Good up to (ms)"
    var pingFairLabel = "Average up to (ms)"
    var pingAutoDeleteUnreachable = "Remove failed servers after ping test"
    var pingAutoDeleteUnreachableDesc = "Delete completed results at or below the threshold (default 1 ms); unfinished tests are kept. Set 0 to preserve 1 ms nodes"
    var pingAutoDeleteThresholdLabel = "Remove at or below (ms)"
    var pingUrlPresets = "Ready-made endpoints"
    var resetToDefaults = "Reset to defaults"
    var aggregateMin = "Best"
    var aggregateAvg = "Average"
    var aggregateMedian = "Median"
    // Server list organization. Falls back to English when a locale does not translate it.
    var sortByNameDesc = "Name (Z-A)"
    var sortByCountry = "Country"
    var sortByProtocol = "Protocol"
    var groupByCountry = "Group by country"
    var onlyReachable = "Only reachable"
    var maxPingLabel = "Max ping"
    var offLabel = "Off"
    var groupLabel = "Group"
    var otherLabel = "Other"
    var filtersLabel = ""; var allProtocols = ""; var groupsWord = ""; var serversWord = ""
    var addServerOrSubscription = ""; var subscriptionLink = ""; var sortDefaultLabel = ""
    var resetFilters = ""; var nothingFound = ""; var groupsAndServers = ""
    // Traffic and app settings. Falls back to English when a locale does not translate it.
    var muxProtocolLabel = "Multiplex protocol"
    var muxMinStreamsLabel = "Minimum streams"
    var muxPadding = "Multiplex padding"
    var muxPaddingDesc = "Pad multiplexed streams so their size pattern is harder to fingerprint"
    var muxBrutal = "TCP Brutal"
    var muxBrutalDesc = "Fixed-rate congestion control; needs server support and both speeds set"
    var muxBrutalUpLabel = "Upload (Mbps)"
    var muxBrutalDownLabel = "Download (Mbps)"
    var outboundSection = "Outbound connections"
    var tcpFastOpen = "TCP Fast Open"
    var tcpFastOpenDesc = "Send the first data with the TCP handshake"
    var tcpMultiPath = "Multipath TCP"
    var tcpMultiPathDesc = "Use several network paths for one connection (MPTCP)"
    var udpFragmentLabel = "UDP fragmentation"
    var udpFragmentDesc = "Split outgoing UDP packets to evade DPI"
    var udpOverTcpLabel = "UDP over TCP"
    var udpOverTcpDesc = "Tunnel UDP inside the TCP stream (Shadowsocks only)"
    var connectTimeoutLabel = "Connect timeout, s (0 — core default)"
    var urlTestIdleTimeoutLabel = "Idle timeout (min, 0 — off)"
    var urlTestInterrupt = "Interrupt connections on switch"
    var urlTestInterruptDesc = "Drop existing connections when auto-select moves to another server"
    var loggingEnabled = "Logging"
    var loggingEnabledDesc = "Record app and core logs. Off stops all logging and keeps nothing on the device"
    // Log viewer levels. Falls back to English when a locale does not translate it.
    var logLevelAll = "All"
    var logLevelDebug = "Debug"
    var logLevelInfo = "Info"
    var logLevelWarning = "Warning"
    var logLevelError = "Error"
    var loadOlderLogs = "Load older entries"
    // OpenVPN credentials. Falls back to English when a locale does not translate it.
    var ovpnCredentialsRequired =
        "This profile signs in with a username and password. Fill in both — the server rejects the connection without them."
    var ovpnCertificateOnlyHint =
        "Certificate-only profile: it authenticates with the client certificate, so no username or password is needed."
    // Dashboard "Check" action and subscription update feedback.
    var checkPing = "Check"
    var pingUnreachable = "unreachable"
    var noServerSelected = "No server selected"
    var subscriptionUpdated = "Subscription updated"
    var subscriptionNoChanges = "No changes found"
    var subscriptionAddedCount = "added"
    var subscriptionUpdatedCount = "updated"
    var subscriptionRemovedCount = "removed"
    var ovpnKeyPasswordLabel = "Private key password"
    var ovpnKeyPasswordRequired =
        "The private key is encrypted. Enter its password, otherwise the tunnel cannot start."
    // Camera permission. Falls back to English when a locale does not translate it.
    var cameraPermissionTitle = "Camera access needed"
    var cameraPermissionMessage =
        "Scanning a QR code needs the camera. Lumen uses it only while the scanner is open."
    var cameraPermissionBlocked =
        "Camera access is turned off for Lumen, so the QR scanner cannot start. Allow the camera in the app settings and try again."
    var openAppSettings = "Open settings"
    // Custom server groups. Falls back to English when a locale does not translate it.
    var newGroup = "New group"
    var groupNameLabel = "Group name"
    var createAction = "Create"
    var renameGroup = "Rename group"
    var deleteGroup = "Delete group"
    var deleteGroupConfirm =
        "Only the group is removed. Its servers are kept and move back to Default."
    var moveToGroup = "Move to group"
    var groupNoGroup = "No group"
    // Provider metadata of a subscription. Falls back to English when a locale does not translate it.
    var providerAnnouncement = "Announcement"
    var providerChannel = "Channel"
    var providerSupport = "Support"
    var providerEmail = "Email"
    var providerWebsite = "Website"
    var providerPremium = "Premium"

    fun groupCountLabel(count: Int): String =
        "$count ${if (localeCode == "ru") russianPlural(count, "группа", "группы", "групп") else groupsWord}"

    fun serverCountLabel(count: Int): String =
        "$count ${if (localeCode == "ru") russianPlural(count, "сервер", "сервера", "серверов") else serverCount}"

    fun copyFrom(src: LumenStrings): LumenStrings = apply {
        src.javaClass.declaredFields.forEach { f ->
            if (f.type == String::class.java) {
                f.isAccessible = true
                f.set(this, f.get(src))
            }
        }
    }
}

private val EN = LumenStrings().apply {
    localeCode = "en"
    home="Home"; servers="Servers"; routing="Routing"; settings="Settings"; logs="Logs"
    noServer="No server selected — tap to choose"; fastest="fastest available"; addNode="Add node"
    searchServers="Search servers…"; pingAll="Ping all"; pinging="Pinging…"
    importClipboard="Import clipboard"; noServers="No servers yet. Add a node or subscription."
    allGroups="All servers"; manual="Manual"; subscriptions="Subscriptions"; addSubscription="Add subscription"
    refresh="Refresh"; delete="Delete"; edit="Edit"; auto="Auto"; never="never"; nodes="nodes"
    updated="updated"; nameOptional="Name (optional)"; cancel="Cancel"; add="Add"
    splitTunneling="Split tunneling"; off="Off"; offDescription="Route all traffic through the VPN"
    vpnOnly="VPN only for selected apps"; vpnOnlyDescription="Only checked apps use the tunnel"
    exclude="Exclude selected apps"; excludeDescription="Checked apps bypass the tunnel"
    appsUsingVpn="Apps using VPN"; appsBypassingVpn="Apps bypassing VPN"; searchApps="Search apps…"
    loadingApps="Loading installed apps…"; hideSystem="Hide system apps"; autoSelect="Auto-select"
    clear="Clear"; vpnEngine="VPN engine"; connection="Connection"
    muxDescription="Reuse one connection for multiple streams"; muxConcurrency="MUX concurrency"
    tlsFragmentation="TLS fragmentation"; tlsDescription="Split TLS ClientHello to evade DPI"
    fragmentPackets="Fragment packets"; fragmentLength="Fragment length"; fragmentDelay="Fragment delay (ms)"
    tunnelMtu="Tunnel MTU"; localProxy="Local proxy"; localInbound="Local SOCKS/HTTP inbound"
    localInboundDescription="Ports 10808 (SOCKS5) and 10809 (HTTP)"; allowLan="Allow LAN connections"
    allowLanDescription="Share the local proxy on your network"; behavior="Behavior"
    proxyOnly="Proxy only"; proxyOnlyDesc="Use the local proxy without routing device traffic through a VPN. Configure apps to use the local proxy. Applies on the next connection."
    autoConnect="Auto-connect on boot"; autoConnectDescription="Reconnect after reboot"
    speedStats="Speed statistics"; speedStatsDesc="Track live VPN speed and bandwidth. Turn off to save battery and resources."
    language="Language"; systemDefault="System default"; speedTest="Speed test"; testing="Testing…"
    runSpeedTest="Run speed test"; export="Export"; noLogs="No log entries yet."
    connectingStatus="Connecting…"
    connectionError="Connection error"; diagnostics="Diagnostics"; openLogs="Open logs"
    preferIpv6="Prefer IPv6"; preferIpv6Description="Use IPv6 when IPv4 and IPv6 are both available"
    blockQuic="Block QUIC"; blockQuicDescription="Reject QUIC on UDP/443 and fall back to TCP"
    sniffRouteOnly="Sniff route only"; sniffRouteOnlyDescription="Use sniffing for routing without replacing destinations"
    socksPort="SOCKS port"; httpPort="HTTP port"
    centerConnect="Connect"; centerConnecting="Connecting…"; centerConnected="Connected"; centerError="Error"
    importFromClipboard="Import from clipboard"; importQrCode="QR code"; importFromFile="From file"; importManually="Manually"
    refreshSubscription="Refresh subscription"; deleteSubscription="Delete subscription"
    autoUpdateOneHour="Auto-update - 1h"; expiresUnlimited="Expires: Unlimited"; daysRemaining="days remaining"
    serverCount="server(s)"; sortByPing="Ping"; pingGroup="Ping group servers"
    sortBy="Sort by:"; sortByName="Name"; subscriptionSettings="Subscription settings"
    trafficSettings="Traffic settings"; appSettings="App settings"; infoSection="INFORMATION"
    version="Version"; community="Community"; back="Back"; requestParameters="Request parameters"
    updates="Updates"; updatesDesc="Check Android releases on GitHub"
    currentVersion="Current version"; latestVersion="Latest Android version"
    checkUpdates="Check for updates"; checkingUpdates="Checking…"
    updateAvailable="A new Android version is available"
    upToDate="You already have the latest Android version"
    downloadUpdate="Download update"; updateCheckFailed="Could not check for updates"
    autoCheckUpdates="Automatically check for updates"; autoCheckUpdatesDesc="Check GitHub when Lumen opens, at most once a day"
    androidReleaseTag="Android release tag"
    directLoad="Load directly"; directLoadDesc="Load subscription bypassing proxy"
    sendHwid="Send HWID"; sendHwidDesc="Send device ID in X-Hwid header"
    allowOverrides="Allow subscription overrides"; allowOverridesDesc="Apply compatible MUX, fragmentation & routing parameters"
    subscriptionAutoUpdate="Auto-update subscriptions"; subscriptionAutoUpdateDesc="Periodically refresh subscription links in the background"
    subscriptionAutoUpdateInterval="Update interval (minutes)"
    subscriptionIncludeRegexLabel="Include filter (regex)"; subscriptionExcludeRegexLabel="Exclude filter (regex)"
    subscriptionUseProxyTun="Load subscriptions through proxy tunnel"; subscriptionUseProxyTunDesc="Route subscription requests via the active VPN tunnel"
    subscriptionAllowHttp="Allow HTTP subscription links"; subscriptionAllowHttpDesc="Permit unencrypted legacy links; subscription tokens may be visible on the network"
    subscriptionConverter="Subscription converter"; subscriptionConverterDesc="Convert subscription links using an external converter service"
    subscriptionConverterUrlLabel="Converter URL"
    subscriptionProfile="Subscription profile"; proxyDns="Proxy DNS"; directDns="Direct DNS"
    autoSelectUrl="Check URL"; checkInterval="Check interval (min)"; toleranceMs="Delay tolerance (ms)"
    appearance="Appearance"; theme="Theme"; domainIpRouting="Domain / IP routing"
    appRouting="App routing"; geoResourceFiles="Geo-resource files"; domainsAndIpDirect="Direct Domains & IP"
    directRulesNotice="Specified addresses bypass proxy. Changes take effect on next connection."
    domainsDirectLabel="Direct domains"; ipCidrDirectLabel="Direct IP / CIDR"
    geoSourceLabel="Geo-resource source"; geoNotLoaded="Files not downloaded yet"
    geoManagedByCore="sing-box extended downloads the exact binary .srs rule sets when a geo rule is used and keeps them in its cache. Legacy geosite.dat and geoip.dat files are not used."
    groupDefault="Default"; importAction="Import"
    themeSettings="Customization"; done="Done";
    dashboardStyle="Dashboard style"; dashboardStyleDefault="Default"; dashboardStyleSlider="Slide to connect"; dashboardStyleCentered="Centered button"; greenTheme="Green"; greenThemeDesc="Dark forest with green accent"
    launcherIcon="App icon"
    launcherIconDesc="The icon may briefly disappear and come back while the launcher reloads it, and some launchers move it to the end of the home screen."
    launcherIconSystem="Follow system"; launcherIconLight="Light"; launcherIconDark="Dark"
    routingPresets="Default rules"; routingPresetsDesc="Ready-made rule sets based on geoip/geosite."
    presetLan="Bypass LAN"; presetAds="Block ads"; presetRu="Bypass Russia"; presetCn="Bypass China"; presetIr="Bypass Iran"; presetGlobalProxy="Global proxy"; customRules="Custom rules"
    deleteAllServers="Delete all servers"; deleteAllServersConfirm="All servers will be removed from the list. Subscriptions stay and can be refreshed again."
    lightTheme="Light"; lightThemeDesc="Light mode with soft colors"; darkTheme="Dark"; darkThemeDesc="Clean dark with blue accent"
    additional="Additional"; materialYou="Material You"
    materialYouDesc="Dynamic colors generated from your wallpaper (Android 12+)"
    materialYouUnavailable="Needs Android 12 or newer — this device keeps the selected palette"
    rosePineTheme="Rosé Pine"; rosePineThemeDesc="Soft muted plum with an iris accent"
    amoledBlack="AMOLED Black"
    amoledBlackDesc="True #000000 surfaces — OLED pixels switch off, saving battery"
    connectionStyleTitle="Connection style"; classicStyle="Classic"; compactStyle="Compact"
    addOrPaste="+ Add or Paste"; swipeOrTapToConnect="Slide to Connect"; swipeOrTapToDisconnect="Slide to Disconnect"
    slideToConnect="Slide to Connect"; slideToDisconnect="Slide to Disconnect"; paste="Paste"
    copyLink="Copy link"; exportQrCode="Export QR code"; ping="Ping"
    subscriptionProperties="Subscription properties"; exportAll="Export all"; exportSelected="Export selected"
    selected="selected"; url="URL"; copied="Copied"; udpPing="UDP Ping"
    address="Address"; action="Action"; directAction="Direct"; proxyAction="Proxy"
    blockAction="Block"; noRulesYet="No domain or IP rules configured"; clearAll="Clear all"
    dnsSettings="DNS settings"; dnsModeSection="DNS mode"; dnsModeAuto="Automatic"
    dnsModeAndroid="Android DNS"; dnsModeSecure="Secure"; dnsModeJson="From JSON"
    dnsModeAutoHint="TCP/UDP 53 is hijacked inside the VPN; direct and proxy resolvers are picked by rules."
    dnsModeAndroidHint="System Android resolver without hijacking inside the VPN."
    dnsModeSecureHint="DoH/DoT through the proxy outbound only; strict Private DNS is checked before start."
    dnsModeJsonHint="DNS comes from your custom JSON config."
    dnsCustomJsonLabel="Custom DNS JSON (dns object)"
    dnsDirectSection="Direct DNS"; dnsProxySection="DNS over proxy"
    dnsServersLabel="Servers (one per line)"; dnsTypeLabel="Type"; dnsStrategyLabel="Strategy"
    dnsIpv4Only="IPv4 only over VPN"; dnsIpv4OnlyDesc="Filter AAAA in the managed proxy DNS"
    dnsBehaviorSection="Behavior"; dnsHijack="Hijack DNS in TUN"
    dnsHijackDesc="Do not let plain DNS queries escape the built-in resolver"
    dnsFakeIp="Fake DNS"; dnsFakeIpDesc="FakeIP is off by default; enable only when needed"
    dnsParallel="Parallel queries"; dnsParallelDesc="Query fallback resolvers simultaneously"
    dnsOptimistic="Optimistic cache"; dnsOptimisticDesc="Serve a stale answer while refreshing in background"
    dnsGeoCheck="DNS geo check"; dnsGeoCheckDesc="Keeps the direct/proxy choice for domain rules"
    dnsHostsSection="Hosts and override"; dnsHostsLabel="Hosts: domain=ip"
    dnsOverride="DNS override"; dnsOverrideDesc="Exact hostname → IPv4 before other DNS rules"
    dnsHostname="Hostname"; dnsIpv4="IPv4"
    vibration="Vibration"; vibrationDesc="Haptic feedback on taps and actions"
    autoReconnectNetwork="Reconnect on network change"; autoReconnectNetworkDesc="Rebuild the tunnel automatically when Wi-Fi and mobile data switch (all protocols)"
    validateProxyDataPath="Validate proxy data path"; validateProxyDataPathDesc="Test HTTPS through the selected server before enabling the VPN (slower startup)"
    showNotification="Show VPN notification"; showNotificationDesc="Keep persistent status notification active"
    notificationSpeed="Speed statistics in notification"; notificationSpeedDesc="Show real-time speed in notification"
    pingSettings="Ping settings"; pingTypeLabel="Ping type"; pingTimeoutLabel="Timeout (ms)"
    pingConcurrencyLabel="Parallel checks"; pingUrlLabel="Ping URL"; pingAutoOnOpen="Ping on open"
    pingAutoOnOpenDesc="Check servers when the list opens"
    pingAutoDeleteUnreachable="Remove failed servers after ping test"; pingAutoDeleteUnreachableDesc="Delete completed results at or below the threshold (default 1 ms); unfinished tests are kept. Set 0 to preserve 1 ms nodes"
    pingAutoDeleteThresholdLabel="Remove at or below (ms)"
    categoryAppearance="APPEARANCE"; categoryConnection="CONNECTION"; categoryTunnel="TUNNEL"
    categoryProviders="PROVIDERS"; categoryOther="OTHER"; perAppProxy="Per-app proxy"
    trafficUsed="Used"; trafficTotal="Total"; expiresLabel="Expires"; unlimited="Unlimited"
    subscriptionInfo="Subscription info"; password="Password"
    editNode="Edit node"; close="Close"; nodeName="Name"; protocolField="Protocol"
    transportLabel="Transport"; pathLabel="Path"; hostHeaderLabel="Host header"; grpcServiceNameLabel="gRPC serviceName"
    securityLabel="Security"; sniLabel="SNI"; alpnLabel="ALPN (comma separated)"
    utlsFingerprintLabel="uTLS fingerprint (chrome, firefox\u2026)"; certificateSha256Label="Certificate public-key SHA-256 (Base64)"; allowInsecureTlsLabel="Allow insecure TLS"
    realityPublicKeyLabel="Reality public key (pbk)"; realityShortIdLabel="Reality short ID (sid)"
    uuidLabel="UUID"; flowLabel="Flow"; noneOption="(none)"; encryptionMethodLabel="Encryption method"
    passwordAuthLabel="Password / auth"; obfsLabel="Obfs (salamander, optional)"; obfsPasswordLabel="Obfs password"
    uuidPasswordLabel="UUID:Password"; congestionControlLabel="Congestion control"
    userPasswordOptionalLabel="user:password (optional)"; privateKeyLabel="Private key"
    peerPublicKeyLabel="Peer public key"; wgAddressLabel="Address (e.g. 10.0.0.2/32)"
    presharedKeyLabel="Pre-shared key (optional)"; allowedIpsLabel="Allowed IPs"
    reservedLabel="Reserved (e.g. 1,2,3 \u2014 optional)"; awgJunkParamsLabel="AmneziaWG junk parameters"
    amneziaCompatible="Amnezia compatible"; amneziaCompatibleDesc="Convert WireGuard to AmneziaWG with default junk parameters"
    disableAmnezia="Disable Amnezia compatibility"; disableAmneziaDesc="Remove the junk parameters and use the server as plain WireGuard"
    openvpnConfigLabel="OpenVPN config (.ovpn contents)"
    autoNodeDescriptionLabel="Automatic selection of the best servers"
    serverLabel="Server"; portLabel="Port"; saveAction="Save"
    filtersLabel="Filters"; allProtocols="All protocols"; groupsWord="groups"; serversWord="servers"
    addServerOrSubscription="Add server or subscription"; subscriptionLink="Subscription link"
    sortDefaultLabel="Default"; resetFilters="Reset"; nothingFound="Nothing matches the filters"
    groupsAndServers="Groups and servers"
    newGroup="New group"; groupNameLabel="Group name"; createAction="Create"
    renameGroup="Rename group"; deleteGroup="Delete group"
    deleteGroupConfirm="Only the group is removed. Its servers are kept and move back to Default."
    moveToGroup="Move to group"; groupNoGroup="No group"
    providerAnnouncement="Announcement"; providerChannel="Channel"; providerSupport="Support"; providerEmail="Email"
    providerWebsite="Website"; providerPremium="Premium"
}

private val RU = LumenStrings().apply {
    localeCode = "ru"
    home="Главная"; servers="Серверы"; routing="Маршрутизация"; settings="Настройки"; logs="Логи"
    noServer="Сервер не выбран — нажмите, чтобы выбрать"; fastest="самый быстрый"; addNode="Добавить сервер"
    searchServers="Поиск серверов…"; pingAll="Проверить все"; pinging="Проверка…"
    importClipboard="Импорт из буфера"; noServers="Серверов пока нет. Добавьте сервер или подписку."
    allGroups="Все серверы"; manual="Вручную"; subscriptions="Подписки"; addSubscription="Добавить подписку"
    refresh="Обновить"; delete="Удалить"; edit="Изменить"; auto="Авто"; never="никогда"; nodes="серверов"
    updated="обновлено"; nameOptional="Название (необязательно)"; cancel="Отмена"; add="Добавить"
    splitTunneling="Раздельная маршрутизация"; off="Выключено"; offDescription="Весь трафик через VPN"
    vpnOnly="VPN только для выбранных"; vpnOnlyDescription="Только отмеченные приложения используют VPN"
    exclude="Исключить выбранные"; excludeDescription="Отмеченные приложения обходят VPN"
    appsUsingVpn="Приложения через VPN"; appsBypassingVpn="Приложения в обход VPN"; searchApps="Поиск приложений…"
    loadingApps="Загрузка приложений…"; hideSystem="Скрыть системные"; autoSelect="Авто-выбор"; clear="Очистить"
    vpnEngine="VPN-движок"; connection="Соединение"; muxDescription="Одно соединение для нескольких потоков"
    muxConcurrency="Параллельность MUX"; tlsFragmentation="Фрагментация TLS"
    tlsDescription="Разделять TLS ClientHello для обхода DPI"; fragmentPackets="Пакеты фрагментации"
    fragmentLength="Длина фрагмента"; fragmentDelay="Задержка фрагмента (мс)"; tunnelMtu="MTU туннеля"
    localProxy="Локальный прокси"; localInbound="Локальный SOCKS/HTTP"
    localInboundDescription="Порты 10808 (SOCKS5) и 10809 (HTTP)"; allowLan="Разрешить подключения из LAN"
    allowLanDescription="Открыть локальный прокси в сети"; behavior="Поведение"
    proxyOnly="Только прокси"; proxyOnlyDesc="Использовать локальный прокси без маршрутизации трафика устройства через VPN. Настройте приложения на локальный прокси. Применяется при следующем подключении."
    autoConnect="Подключаться при запуске"; autoConnectDescription="Переподключаться после перезагрузки"
    speedStats="Статистика скорости"; speedStatsDesc="Отслеживание и измерение скорости трафика VPN. Отключите для экономии энергии."
    language="Язык"; systemDefault="Как в системе"; speedTest="Тест скорости"; testing="Проверка…"
    runSpeedTest="Запустить тест"; export="Экспорт"; noLogs="Записей пока нет."
    connectingStatus="Подключение…"
    connectionError="Ошибка подключения"
    diagnostics="Диагностика"; openLogs="Открыть логи"
    preferIpv6="Предпочитать IPv6"; preferIpv6Description="Использовать IPv6, когда доступны IPv4 и IPv6"
    blockQuic="Блокировать QUIC"; blockQuicDescription="Блокировать QUIC на UDP/443 с переходом на TCP"
    sniffRouteOnly="Сниффинг только для маршрутов"; sniffRouteOnlyDescription="Использовать сниффинг для маршрутизации без замены адреса назначения"
    socksPort="Порт SOCKS"; httpPort="Порт HTTP"
    centerConnect="Подключиться"; centerConnecting="Подключение…"; centerConnected="Подключено"; centerError="Ошибка"
    importFromClipboard="Вставить из буфера"; importQrCode="QR-код"; importFromFile="Из файла"; importManually="Вручную"
    refreshSubscription="Обновить подписку"; deleteSubscription="Удалить подписку"
    autoUpdateOneHour="Автообновление - 1 ч."; expiresUnlimited="Истекает: Безлимитно"; daysRemaining="дней осталось"
    serverCount="сервер(ов)"; sortByPing="Пинг"; pingGroup="Проверить пинг группы"
    sortBy="Сортировать по:"; sortByName="Имя"; subscriptionSettings="Настройки подписок"
    trafficSettings="Настройки трафика"; appSettings="Настройки приложения"; infoSection="ИНФОРМАЦИЯ"
    version="Версия"; community="Сообщество"; back="Назад"; requestParameters="Параметры запроса"
    updates="Обновления"; updatesDesc="Проверка Android-релизов на GitHub"
    currentVersion="Текущая версия"; latestVersion="Последняя Android-версия"
    checkUpdates="Проверить обновления"; checkingUpdates="Проверка…"
    updateAvailable="Доступна новая версия для Android"
    upToDate="У вас уже последняя версия для Android"
    downloadUpdate="Скачать обновление"; updateCheckFailed="Не удалось проверить обновления"
    autoCheckUpdates="Автоматически проверять обновления"; autoCheckUpdatesDesc="Проверять GitHub при запуске Lumen, не чаще одного раза в день"
    androidReleaseTag="Тег Android-релиза"
    directLoad="Загружать напрямую"; directLoadDesc="Подписка загружается в обход выбранного прокси-сервера"
    sendHwid="Отправлять HWID"; sendHwidDesc="Передавать идентификатор устройства в заголовке X-Hwid"
    allowOverrides="Разрешить настройки из подписки"; allowOverridesDesc="Применять совместимые параметры MUX, фрагментации и маршрутизации"
    subscriptionAutoUpdate="Автообновление подписок"; subscriptionAutoUpdateDesc="Периодически обновлять ссылки подписок в фоне"
    subscriptionAutoUpdateInterval="Интервал обновления (мин)"
    subscriptionIncludeRegexLabel="Фильтр включения (regex)"; subscriptionExcludeRegexLabel="Фильтр исключения (regex)"
    subscriptionUseProxyTun="Загружать подписки через прокси-туннель"; subscriptionUseProxyTunDesc="Отправлять запросы подписки через активный VPN-туннель"
    subscriptionAllowHttp="Разрешить HTTP-ссылки подписок"; subscriptionAllowHttpDesc="Разрешить незашифрованные ссылки старых панелей; токен подписки может быть виден в сети"
    subscriptionConverter="Конвертер подписок"; subscriptionConverterDesc="Преобразовывать ссылки подписок через внешний сервис-конвертер"
    subscriptionConverterUrlLabel="URL конвертера"
    subscriptionProfile="Профиль подписки"; proxyDns="DNS через прокси"; directDns="DNS напрямую"
    autoSelectUrl="URL проверки"; checkInterval="Интервал проверки (мин)"; toleranceMs="Допуск задержки (мс)"
    appearance="Оформление"; theme="Тема"; domainIpRouting="Маршрутизация по домену/IP"
    appRouting="Маршрутизация приложений"; geoResourceFiles="Файлы георесурсов"; domainsAndIpDirect="Домены и IP напрямую"
    directRulesNotice="Указанные адреса обходят прокси. Изменения применятся при следующем подключении."
    domainsDirectLabel="Домены напрямую"; ipCidrDirectLabel="IP / CIDR напрямую"
    geoSourceLabel="Источник георесурсов"; geoNotLoaded="Файлы ещё не загружены"
    geoManagedByCore="sing-box extended загружает точные бинарные наборы правил .srs при использовании geo-правила и сохраняет их в кэше. Устаревшие geosite.dat и geoip.dat не используются."
    groupDefault="Default"; importAction="Импорт"
    themeSettings="Персонализация"; done="Готово";
    dashboardStyle="Стиль дашборда"; dashboardStyleDefault="По умолчанию"; dashboardStyleSlider="Слайдер подключения"; dashboardStyleCentered="Кнопка по центру"; greenTheme="Зелёная"; greenThemeDesc="Тёмный лес с зелёным акцентом"
    launcherIcon="Значок приложения"
    launcherIconDesc="Значок может ненадолго исчезнуть и появиться снова, пока лаунчер его перезагружает, а некоторые лаунчеры перенесут его в конец рабочего стола."
    launcherIconSystem="Как в системе"; launcherIconLight="Светлый"; launcherIconDark="Тёмный"
    routingPresets="Правила по умолчанию"; routingPresetsDesc="Готовые наборы правил на основе geoip/geosite."
    presetLan="Обход локальной сети"; presetAds="Блокировать рекламу"; presetRu="Обход России"; presetCn="Обход Китая"; presetIr="Обход Ирана"; presetGlobalProxy="Глобальный прокси"; customRules="Свои правила"
    deleteAllServers="Удалить все серверы"; deleteAllServersConfirm="Все серверы будут удалены из списка. Подписки останутся и их можно будет обновить заново."
    lightTheme="Светлая"; lightThemeDesc="Светлый режим с мягкими цветами"; darkTheme="Тёмная"; darkThemeDesc="Чистый тёмный с голубым акцентом"
    additional="Дополнительно"; materialYou="Material You"
    materialYouDesc="Динамические цвета из ваших обоев (Android 12+)"
    materialYouUnavailable="Нужен Android 12 или новее — на этом устройстве остаётся выбранная палитра"
    rosePineTheme="Rosé Pine"; rosePineThemeDesc="Мягкий приглушённый сливовый с акцентом ирис"
    amoledBlack="AMOLED чёрный"
    amoledBlackDesc="Настоящий #000000 — пиксели OLED гаснут и экономят заряд"
    connectionStyleTitle="Стиль подключения"; classicStyle="Классический"; compactStyle="Компактный"
    addOrPaste="+ Добавить или Вставить"; swipeOrTapToConnect="Проведите для подключения"; swipeOrTapToDisconnect="Проведите для отключения"
    slideToConnect="Проведите для подключения"; slideToDisconnect="Проведите для отключения"; paste="Вставить"
    copyLink="Копировать ссылку"; exportQrCode="Экспорт в QR-код"; ping="Пинг"
    subscriptionProperties="Свойства подписки"; exportAll="Экспорт всех"; exportSelected="Экспорт выбранных"
    selected="выбрано"; url="URL"; copied="Скопировано"; udpPing="UDP Пинг"
    address="Адрес"; action="Действие"; directAction="Прямой"; proxyAction="Прокси"
    blockAction="Блокировать"; noRulesYet="Правила по доменам и IP не заданы"; clearAll="Очистить все"
    dnsSettings="Настройки DNS"; dnsModeSection="Режим DNS"; dnsModeAuto="Автоматически"
    dnsModeAndroid="DNS Android"; dnsModeSecure="Защищённый"; dnsModeJson="Из JSON"
    dnsModeAutoHint="TCP/UDP 53 перехватывается внутри VPN, прямые и proxy resolver подбираются по правилам."
    dnsModeAndroidHint="Системный resolver Android без перехвата внутри VPN."
    dnsModeSecureHint="DoH/DoT только через proxy outbound; строгий Private DNS проверяется до старта."
    dnsModeJsonHint="DNS берётся из пользовательского JSON-конфига."
    dnsCustomJsonLabel="Пользовательский DNS JSON (объект dns)"
    dnsDirectSection="Прямой DNS"; dnsProxySection="DNS через прокси"
    dnsServersLabel="Серверы (по одному в строке)"; dnsTypeLabel="Тип"; dnsStrategyLabel="Стратегия"
    dnsIpv4Only="Только IPv4 через VPN"; dnsIpv4OnlyDesc="Фильтровать AAAA в управляемом proxy DNS"
    dnsBehaviorSection="Поведение"; dnsHijack="Перехватывать DNS в TUN"
    dnsHijackDesc="Не выпускать обычные DNS-запросы мимо встроенного resolver"
    dnsFakeIp="Fake DNS"; dnsFakeIpDesc="FakeIP выключен по умолчанию; включайте только при необходимости"
    dnsParallel="Параллельные запросы"; dnsParallelDesc="Опрашивать резервные resolver одновременно"
    dnsOptimistic="Оптимистичный кэш"; dnsOptimisticDesc="Разрешить устаревший ответ с обновлением в фоне"
    dnsGeoCheck="Geo-проверка DNS"; dnsGeoCheckDesc="Сохраняет прямой/proxy выбор для доменных правил"
    dnsHostsSection="Hosts и override"; dnsHostsLabel="Hosts: domain=ip"
    dnsOverride="DNS override"; dnsOverrideDesc="Точный hostname → IPv4 до остальных DNS-правил"
    dnsHostname="Hostname"; dnsIpv4="IPv4"
    vibration="Вибрация"; vibrationDesc="Тактильный отклик при нажатиях и действиях"
    autoReconnectNetwork="Переподключение при смене сети"; autoReconnectNetworkDesc="Автоматически пересобирать туннель при переключении Wi-Fi и мобильного интернета (все протоколы)"
    validateProxyDataPath="Проверять передачу данных через прокси"; validateProxyDataPathDesc="Проверять HTTPS через выбранный сервер перед включением VPN (запуск будет дольше)"
    copyAction="Копировать"
    geoDownloadAction="Скачать файлы правил"; geoUpdating="Загрузка…"
    socks5Auth="Socks5 авторизация"
    socks5AuthDesc="Защитить локальный прокси от несанкционированного доступа. HTTP-прокси будет недоступен. Соединение будет защищено и для подключений из LAN."
    socks5Login="Socks5 логин"; socks5PasswordLabel="Socks5 пароль"; socks5Reset="Сбросить логин/пароль"
    showNotification="Показывать уведомление VPN"; showNotificationDesc="Постоянное уведомление о статусе подключения"
    notificationSpeed="Статистика скорости в уведомлении"; notificationSpeedDesc="Отображать текущую скорость подключения"
    pingSettings="Настройки пинга"; pingTypeLabel="Тип проверки"; pingTimeoutLabel="Таймаут (мс)"
    pingConcurrencyLabel="Параллельных проверок"; pingUrlLabel="URL проверки"; pingAutoOnOpen="Пинг при открытии"
    pingAutoOnOpenDesc="Проверять серверы при открытии списка"
    pingAutoDeleteUnreachable="Удалять неисправные серверы после проверки"; pingAutoDeleteUnreachableDesc="Удалять завершённые результаты не выше порога (по умолчанию 1 мс); незавершённые проверки сохраняются. Поставьте 0, чтобы сохранять узлы с ответом 1 мс"
    pingAutoDeleteThresholdLabel="Удалять при значении не выше (мс)"
    categoryAppearance="ОФОРМЛЕНИЕ"; categoryConnection="СОЕДИНЕНИЕ"; categoryTunnel="ТУННЕЛЬ"
    categoryProviders="ПОДПИСКИ"; categoryOther="ПРОЧЕЕ"; perAppProxy="Прокси по приложениям"
    trafficUsed="Использовано"; trafficTotal="Всего"; expiresLabel="Истекает"; unlimited="Безлимит"
    subscriptionInfo="Информация о подписке"; password="Пароль"
    editNode="Изменить сервер"; close="Закрыть"; nodeName="Имя"; protocolField="Протокол"
    transportLabel="Транспорт"; pathLabel="Путь"; hostHeaderLabel="Заголовок Host"; grpcServiceNameLabel="gRPC serviceName"
    securityLabel="Безопасность"; sniLabel="SNI"; alpnLabel="ALPN (через запятую)"
    utlsFingerprintLabel="Отпечаток uTLS (chrome, firefox\u2026)"; certificateSha256Label="SHA-256 публичного ключа сертификата (Base64)"; allowInsecureTlsLabel="Разрешить небезопасный TLS"
    realityPublicKeyLabel="Публичный ключ Reality (pbk)"; realityShortIdLabel="Короткий ID Reality (sid)"
    uuidLabel="UUID"; flowLabel="Flow"; noneOption="(нет)"; encryptionMethodLabel="Метод шифрования"
    passwordAuthLabel="Пароль / авторизация"; obfsLabel="Obfs (salamander, опционально)"; obfsPasswordLabel="Пароль Obfs"
    uuidPasswordLabel="UUID:Пароль"; congestionControlLabel="Контроль перегрузки"
    userPasswordOptionalLabel="логин:пароль (опционально)"; privateKeyLabel="Приватный ключ"
    peerPublicKeyLabel="Публичный ключ пира"; wgAddressLabel="Адрес (например, 10.0.0.2/32)"
    presharedKeyLabel="Предварительный ключ (опционально)"; allowedIpsLabel="Разрешённые IP"
    reservedLabel="Reserved (например, 1,2,3 \u2014 опционально)"; awgJunkParamsLabel="Мусорные параметры AmneziaWG"
    amneziaCompatible="Совместимость с Amnezia"; amneziaCompatibleDesc="Превратить WireGuard в AmneziaWG с параметрами по умолчанию"
    disableAmnezia="Отключить совместимость с Amnezia"; disableAmneziaDesc="Убрать мусорные параметры и использовать сервер как обычный WireGuard"
    useProxyLabel="Использовать прокси"; proxyServerLabel="Прокси-сервер"
    proxyUsernameLabel="Логин прокси (опционально)"; proxyPasswordLabel="Пароль прокси (опционально)"
    obfsProxyHint="obfsproxy работает внутри Lumen, отдельный бинарник не нужен"
    openvpnConfigLabel="Конфиг OpenVPN (содержимое .ovpn)"
    autoNodeDescriptionLabel="Автовыбор лучших серверов"
    serverLabel="Сервер"; portLabel="Порт"; saveAction="Сохранить"
    filtersLabel="Фильтры"; allProtocols="Все протоколы"; groupsWord="групп"; serversWord="серверов"
    addServerOrSubscription="Добавить сервер или подписку"; subscriptionLink="Ссылка на подписку"
    sortDefaultLabel="По умолчанию"; resetFilters="Сбросить"; nothingFound="Ничего не найдено по фильтрам"
    groupsAndServers="Группы и серверы"
    sortByNameDesc="Имя (Я\u2192А)"; sortByCountry="Страна"; sortByProtocol="Протокол"
    groupByCountry="Группировать по странам"; onlyReachable="Только доступные"
    maxPingLabel="Макс. пинг"; offLabel="Выкл"; groupLabel="Группа"; otherLabel="Прочее"
    pingAttemptsLabel="Попыток на сервер"; pingAggregateLabel="Результат из попыток"
    pingRetryDelayLabel="Пауза между попытками (мс)"; pingThresholds="Цвета задержки"
    pingGoodLabel="Хорошо до (мс)"; pingFairLabel="Средне до (мс)"
    pingUrlPresets="Готовые адреса"; resetToDefaults="Сбросить к значениям по умолчанию"
    aggregateMin="Лучшая"; aggregateAvg="Средняя"; aggregateMedian="Медиана"
    speedLabel="Скорость"; sessionLabel="Сессия"
    masqueProfileIdLabel="ID профиля"; masqueAuthTokenLabel="Токен авторизации"
    wgMtuLabel="MTU (опционально)"; wgDnsLabel="DNS-серверы (через запятую)"
    wgKeepaliveLabel="Persistent keepalive, с"; awgHeadersLabel="Магические заголовки AmneziaWG"
    telemetryEnabled="Анонимная диагностика"
    telemetryEnabledDesc="Отправлять версию приложения и анонимную статистику ошибок, чтобы помочь их исправить"
    muxProtocolLabel="Протокол мультиплексирования"; muxMinStreamsLabel="Минимум потоков"
    muxPadding="Заполнение MUX"; muxPaddingDesc="Добавлять случайное заполнение, чтобы размеры потоков было сложнее определить"
    muxBrutal="TCP Brutal"; muxBrutalDesc="Контроль перегрузки с фиксированной скоростью; нужна поддержка сервера и обе скорости"
    muxBrutalUpLabel="Отдача (Мбит/с)"; muxBrutalDownLabel="Приём (Мбит/с)"
    outboundSection="Исходящие соединения"
    tcpFastOpen="TCP Fast Open"; tcpFastOpenDesc="Отправлять первые данные вместе с рукопожатием TCP"
    tcpMultiPath="Multipath TCP"; tcpMultiPathDesc="Использовать несколько сетевых путей для одного соединения (MPTCP)"
    udpFragmentLabel="Фрагментация UDP"; udpFragmentDesc="Разбивать исходящие UDP-пакеты для обхода DPI"
    udpOverTcpLabel="UDP через TCP"; udpOverTcpDesc="Передавать UDP внутри TCP-потока (только Shadowsocks)"
    connectTimeoutLabel="Таймаут подключения, с (0 — по умолчанию)"
    urlTestIdleTimeoutLabel="Таймаут простоя (мин, 0 — выкл)"
    urlTestInterrupt="Разрывать соединения при переключении"
    urlTestInterruptDesc="Закрывать текущие соединения, когда автовыбор переходит на другой сервер"
    loggingEnabled="Логирование"
    loggingEnabledDesc="Записывать логи приложения и ядра. При выключении логи не ведутся и на устройстве ничего не хранится"
    logLevelAll="Все"; logLevelDebug="Отладка"; logLevelInfo="Информация"
    logLevelWarning="Предупреждения"; logLevelError="Ошибки"
    loadOlderLogs="Загрузить более старые записи"
    ovpnCredentialsRequired="Этот профиль входит по логину и паролю. Заполните оба поля — без них сервер отклонит подключение."
    ovpnCertificateOnlyHint="Профиль только с сертификатом: вход выполняется клиентским сертификатом, логин и пароль не нужны."
    checkPing="Проверить"; pingUnreachable="недоступен"; noServerSelected="Сервер не выбран"
    subscriptionUpdated="Подписка обновлена"; subscriptionNoChanges="Изменений нет"
    subscriptionAddedCount="добавлено"; subscriptionUpdatedCount="обновлено"; subscriptionRemovedCount="удалено"
    ovpnKeyPasswordLabel="Пароль приватного ключа"
    ovpnKeyPasswordRequired="Приватный ключ зашифрован. Укажите пароль, иначе туннель не запустится."
    cameraPermissionTitle="Нужен доступ к камере"
    cameraPermissionMessage="Для сканирования QR-кода нужна камера. Lumen использует её только пока открыт сканер."
    cameraPermissionBlocked="Доступ к камере для Lumen отключён, поэтому сканер QR-кодов не запускается. Разрешите камеру в настройках приложения и повторите."
    openAppSettings="Открыть настройки"
    newGroup="Новая группа"; groupNameLabel="Название группы"; createAction="Создать"
    renameGroup="Переименовать группу"; deleteGroup="Удалить группу"
    deleteGroupConfirm="Удалится только группа. Её серверы останутся и вернутся в «По умолчанию»."
    moveToGroup="Переместить в группу"; groupNoGroup="Без группы"
    providerAnnouncement="Объявление"; providerChannel="Канал"; providerSupport="Поддержка"; providerEmail="Почта"
    providerWebsite="Сайт"; providerPremium="Премиум"
}

private val ZH = LumenStrings().copyFrom(EN).apply {
    localeCode = "zh"
    home="主页"; servers="服务器"; routing="路由"; settings="设置"; logs="日志"
    subscriptions="订阅"; addSubscription="添加订阅"; searchServers="搜索服务器…"
    hideSystem="隐藏系统应用"; autoSelect="自动选择"; clear="清除"
    language="语言"; systemDefault="跟随系统"; speedTest="速度测试"; runSpeedTest="开始测试"
    connectingStatus="正在连接…"
    connectionError="连接错误"; diagnostics="诊断"; openLogs="打开日志"
    preferIpv6="优先使用 IPv6"; preferIpv6Description="IPv4 和 IPv6 都可用时优先使用 IPv6"
    blockQuic="阻止 QUIC"; blockQuicDescription="阻止 UDP/443 上的 QUIC 并回退到 TCP"
    sniffRouteOnly="仅用于路由嗅探"; sniffRouteOnlyDescription="嗅探仅用于路由，不替换目标地址"
    socksPort="SOCKS 端口"; httpPort="HTTP 端口"
    centerConnect="连接"; centerConnecting="正在连接…"; centerConnected="已连接"; centerError="错误"
    importFromClipboard="剪贴板导入"; importQrCode="二维码"; importFromFile="从文件导入"; importManually="手动添加"
    refreshSubscription="刷新订阅"; deleteSubscription="删除订阅"
    autoUpdateOneHour="自动更新 - 1小时"; expiresUnlimited="到期时间: 无限制"; daysRemaining="天剩余"
    serverCount="个服务器"; sortByPing="按延迟排序"; pingGroup="测试分组延迟"
    sortBy="排序方式:"; sortByName="名称"; subscriptionSettings="订阅设置"
    trafficSettings="流量设置"; appSettings="应用设置"; infoSection="信息"
    version="版本"; community="社区"; back="返回"; requestParameters="请求参数"
    updates="更新"; updatesDesc="检查 GitHub 上的 Android 版本"
    currentVersion="当前版本"; latestVersion="最新 Android 版本"
    checkUpdates="检查更新"; checkingUpdates="正在检查…"
    updateAvailable="有新的 Android 版本可用"; upToDate="当前已是最新 Android 版本"
    downloadUpdate="下载更新"; updateCheckFailed="无法检查更新"; androidReleaseTag="Android 版本标签"
    autoCheckUpdates="自动检查更新"; autoCheckUpdatesDesc="打开 Lumen 时检查 GitHub，每天最多一次"
    directLoad="直接加载"; directLoadDesc="绕过代理加载订阅"
    sendHwid="发送 HWID"; sendHwidDesc="在 X-Hwid 标头中发送设备 ID"
    allowOverrides="允许订阅覆盖"; allowOverridesDesc="应用兼容的 MUX、分片和路由参数"
    subscriptionAutoUpdate="自动更新订阅"; subscriptionAutoUpdateDesc="在后台定期刷新订阅链接"
    subscriptionAutoUpdateInterval="更新间隔（分钟）"
    subscriptionIncludeRegexLabel="包含过滤（正则）"; subscriptionExcludeRegexLabel="排除过滤（正则）"
    subscriptionUseProxyTun="通过代理隧道加载订阅"; subscriptionUseProxyTunDesc="通过当前 VPN 隧道发送订阅请求"
    subscriptionAllowHttp="允许 HTTP 订阅链接"; subscriptionAllowHttpDesc="允许未加密的旧式链接；订阅令牌可能会在网络中暴露"
    subscriptionConverter="订阅转换器"; subscriptionConverterDesc="使用外部转换服务转换订阅链接"
    subscriptionConverterUrlLabel="转换器 URL"
    subscriptionProfile="订阅配置"; proxyDns="代理 DNS"; directDns="直连 DNS"
    autoSelectUrl="检查 URL"; checkInterval="检查间隔 (分钟)"; toleranceMs="延迟容忍度 (毫秒)"
    appearance="外观"; theme="主题"; domainIpRouting="域名 / IP 路由"
    appRouting="应用路由"; geoResourceFiles="Geo 资源文件"; domainsAndIpDirect="直连域名与 IP"
    directRulesNotice="指定的地址将绕过代理。更改将在下次连接时生效。"
    domainsDirectLabel="直连域名"; ipCidrDirectLabel="直连 IP / CIDR"
    geoSourceLabel="Geo 资源来源"; geoNotLoaded="文件尚未下载"
    geoManagedByCore="使用 Geo 规则时，sing-box extended 会下载对应的二进制 .srs 规则集并保存在缓存中。不再使用旧版 geosite.dat 和 geoip.dat。"
    groupDefault="默认"; importAction="导入"
    themeSettings="个性化"; done="完成";
    dashboardStyle="仪表盘样式"; dashboardStyleDefault="默认"; dashboardStyleSlider="滑动连接"; dashboardStyleCentered="居中按钮"; greenTheme="绿色"; greenThemeDesc="带绿色点缀的深色森林"
    launcherIcon="应用图标"
    launcherIconDesc="启动器重新加载图标时，图标可能会短暂消失后再出现；部分启动器会把它移到桌面末尾。"
    launcherIconSystem="跟随系统"; launcherIconLight="浅色"; launcherIconDark="深色"
    routingPresets="默认规则"; routingPresetsDesc="基于 geoip/geosite 的现成规则集。"
    presetLan="绕过局域网"; presetAds="拦截广告"; presetRu="绕过俄罗斯"; presetCn="绕过中国"; presetIr="绕过伊朗"; presetGlobalProxy="全局代理"; customRules="自定义规则"
    deleteAllServers="删除所有服务器"; deleteAllServersConfirm="列表中的所有服务器将被删除。订阅会保留，可以重新更新。"
    lightTheme="浅色"; lightThemeDesc="柔和色彩的浅色模式"; darkTheme="深色"; darkThemeDesc="带蓝色点缀的纯正深色"
    additional="附加设置"; materialYou="Material You"
    materialYouDesc="根据壁纸生成动态配色（Android 12 及以上）"
    materialYouUnavailable="需要 Android 12 或更高版本 — 本设备将保持所选配色"
    rosePineTheme="Rosé Pine"; rosePineThemeDesc="柔和梅紫配鸢尾紫点缀"
    amoledBlack="AMOLED 纯黑"
    amoledBlackDesc="真正的 #000000 背景 — OLED 像素完全熄灭，更省电"
    connectionStyleTitle="连接样式"; classicStyle="经典"; compactStyle="紧凑"
    noServer="未选择服务器 — 点击选择"; fastest="最快可用"; addNode="添加节点"
    pingAll="全部测延迟"; pinging="测试中…"; importClipboard="从剪贴板导入"
    noServers="还没有服务器。请添加节点或订阅。"; allGroups="全部服务器"; manual="手动"
    refresh="刷新"; delete="删除"; edit="编辑"; auto="自动"; never="从未"; nodes="个节点"
    updated="已更新"; nameOptional="名称（可选）"; cancel="取消"; add="添加"
    splitTunneling="分流代理"; off="关闭"; offDescription="所有流量走 VPN"
    vpnOnly="仅所选应用使用 VPN"; vpnOnlyDescription="仅勾选的应用使用隔离道"
    exclude="排除所选应用"; excludeDescription="勾选的应用绕过隔离道"
    appsUsingVpn="使用 VPN 的应用"; appsBypassingVpn="绕过 VPN 的应用"; searchApps="搜索应用…"
    loadingApps="正在加载已安装应用…"; vpnEngine="VPN 引擎"; connection="连接"
    muxDescription="多个流复用一个连接"; muxConcurrency="MUX 并发数"
    tlsFragmentation="TLS 分片"; tlsDescription="分割 TLS ClientHello 以绕过 DPI"
    fragmentPackets="分片数据包"; fragmentLength="分片长度"; fragmentDelay="分片延迟 (毫秒)"
    tunnelMtu="隔离道 MTU"; localProxy="本地代理"; localInbound="本地 SOCKS/HTTP 入口"
    localInboundDescription="端口 10808 (SOCKS5) 和 10809 (HTTP)"; allowLan="允许局域网连接"
    allowLanDescription="在网络中共享本地代理"; behavior="行为"
    proxyOnly="仅代理"; proxyOnlyDesc="仅使用本地代理，不通过 VPN 路由设备流量。请将应用配置为使用本地代理。下次连接时生效。"
    autoConnect="开机自动连接"; autoConnectDescription="重启后重新连接"
    speedStats="速度统计"; speedStatsDesc="跟踪并测量 VPN 实时流量速度。关闭以节省电量和资源。"
    testing="测试中…"; export="导出"; noLogs="暂无日志。"
    paste="粘贴"; copyLink="复制链接"; exportQrCode="导出二维码"; ping="延迟"
    subscriptionProperties="订阅属性"; exportAll="全部导出"; exportSelected="导出所选"
    selected="已选"; url="链接"; copied="已复制"; udpPing="UDP 延迟"
    address="地址"; action="动作"; directAction="直连"; proxyAction="代理"
    blockAction="拦截"; noRulesYet="尚未配置域名或 IP 规则"; clearAll="全部清除"
    addOrPaste="+ 添加或粘贴"; swipeOrTapToConnect="滑动连接"; swipeOrTapToDisconnect="滑动断开"
    slideToConnect="滑动连接"; slideToDisconnect="滑动断开"
    dnsSettings="DNS 设置"; dnsModeSection="DNS 模式"; dnsModeAuto="自动"
    dnsModeAndroid="Android DNS"; dnsModeSecure="安全"; dnsModeJson="来自 JSON"
    dnsModeAutoHint="在 VPN 内接管 TCP/UDP 53，按规则选择直连与代理解析器。"
    dnsModeAndroidHint="使用系统 Android 解析器，不在 VPN 内接管。"
    dnsModeSecureHint="仅通过代理出口使用 DoH/DoT；启动前检查严格私密 DNS。"
    dnsModeJsonHint="DNS 来自你的自定义 JSON 配置。"
    dnsCustomJsonLabel="自定义 DNS JSON（dns 对象）"
    dnsDirectSection="直连 DNS"; dnsProxySection="代理 DNS"
    dnsServersLabel="服务器（每行一个）"; dnsTypeLabel="类型"; dnsStrategyLabel="策略"
    dnsIpv4Only="VPN 内仅 IPv4"; dnsIpv4OnlyDesc="在托管代理 DNS 中过滤 AAAA"
    dnsBehaviorSection="行为"; dnsHijack="在 TUN 中接管 DNS"
    dnsHijackDesc="不让明文 DNS 查询绕过内置解析器"
    dnsFakeIp="Fake DNS"; dnsFakeIpDesc="FakeIP 默认关闭，仅在需要时开启"
    dnsParallel="并行查询"; dnsParallelDesc="同时查询备用解析器"
    dnsOptimistic="乐观缓存"; dnsOptimisticDesc="先返回旧结果，后台刷新"
    dnsGeoCheck="DNS 地理检查"; dnsGeoCheckDesc="保留域名规则的直连/代理选择"
    dnsHostsSection="Hosts 与覆盖"; dnsHostsLabel="Hosts: domain=ip"
    dnsOverride="DNS 覆盖"; dnsOverrideDesc="精确主机名 → IPv4，优先于其他规则"
    dnsHostname="主机名"; dnsIpv4="IPv4"
    vibration="震动"; vibrationDesc="点击和操作时的触觉反馈"
    pingSettings="延迟设置"; pingTypeLabel="测试类型"; pingTimeoutLabel="超时 (毫秒)"
    pingConcurrencyLabel="并发测试数"; pingUrlLabel="测试链接"; pingAutoOnOpen="打开时测试"
    pingAutoOnOpenDesc="打开列表时自动测试服务器"
    pingAutoDeleteUnreachable="测试后删除故障服务器"; pingAutoDeleteUnreachableDesc="删除不高于阈值的已完成结果；未完成测试会保留"
    pingAutoDeleteThresholdLabel="删除不高于（毫秒）"
    categoryAppearance="外观"; categoryConnection="连接"; categoryTunnel="隔离道"
    categoryProviders="订阅源"; categoryOther="其他"; perAppProxy="分应用代理"
    trafficUsed="已用"; trafficTotal="总量"; expiresLabel="到期"; unlimited="无限制"
    subscriptionInfo="订阅信息"; password="密码"
    editNode="编辑节点"; close="关闭"; nodeName="名称"; protocolField="协议"
    transportLabel="传输方式"; pathLabel="路径"; hostHeaderLabel="Host 头"; grpcServiceNameLabel="gRPC 服务名"
    securityLabel="安全"; sniLabel="SNI"; alpnLabel="ALPN（逗号分隔）"
    utlsFingerprintLabel="uTLS 指纹（chrome、firefox\u2026）"; certificateSha256Label="证书公钥 SHA-256（Base64）"; allowInsecureTlsLabel="允许不安全的 TLS"
    realityPublicKeyLabel="Reality 公钥（pbk）"; realityShortIdLabel="Reality 短 ID（sid）"
    uuidLabel="UUID"; flowLabel="Flow"; noneOption="（无）"; encryptionMethodLabel="加密方式"
    passwordAuthLabel="密码 / 认证"; obfsLabel="Obfs（salamander，可选）"; obfsPasswordLabel="Obfs 密码"
    uuidPasswordLabel="UUID:密码"; congestionControlLabel="拥塞控制"
    userPasswordOptionalLabel="用户名:密码（可选）"; privateKeyLabel="私钥"
    peerPublicKeyLabel="对端公钥"; wgAddressLabel="地址（例如 10.0.0.2/32）"
    presharedKeyLabel="预共享密钥（可选）"; allowedIpsLabel="允许的 IP"
    reservedLabel="Reserved（例如 1,2,3 \u2014 可选）"; awgJunkParamsLabel="AmneziaWG 垃圾参数"
    amneziaCompatible="兼容 Amnezia"; amneziaCompatibleDesc="将 WireGuard 转为 AmneziaWG，使用默认垃圾参数"
    openvpnConfigLabel="OpenVPN 配置（.ovpn 内容）"
    autoNodeDescriptionLabel="自动选择最佳服务器"
    serverLabel="服务器"; portLabel="端口"; saveAction="保存"
    speedLabel="速度"; sessionLabel="会话"
    showNotification="显示 VPN 通知"; showNotificationDesc="显示持续连接状态通知"
    notificationSpeed="通知中的速度统计"; notificationSpeedDesc="显示当前连接速度"
    autoReconnectNetwork="网络变化时重新连接"; autoReconnectNetworkDesc="Wi-Fi 与移动网络切换时重建隧道"
    validateProxyDataPath="验证代理数据通路"; validateProxyDataPathDesc="启用 VPN 前通过所选服务器测试 HTTPS（启动会变慢）"
    disableAmnezia="禁用 Amnezia 兼容模式"; disableAmneziaDesc="移除混淆参数并作为普通 WireGuard 使用"
    useProxyLabel="使用代理"; proxyServerLabel="代理服务器"; proxyUsernameLabel="代理用户名（可选）"; proxyPasswordLabel="代理密码（可选）"
    obfsProxyHint="obfsproxy 已内置于 Lumen，无需额外程序"
    pingAttemptsLabel="每台服务器的尝试次数"; pingAggregateLabel="尝试结果"; pingRetryDelayLabel="尝试间隔（毫秒）"
    pingThresholds="延迟颜色阈值"; pingGoodLabel="良好（毫秒以内）"; pingFairLabel="一般（毫秒以内）"
    pingUrlPresets="预设地址"; resetToDefaults="恢复默认值"; aggregateMin="最佳"; aggregateAvg="平均"; aggregateMedian="中位数"
    sortByNameDesc="名称（降序）"; sortByCountry="国家/地区"; sortByProtocol="协议"
    groupByCountry="按国家/地区分组"; onlyReachable="仅显示可连接"; maxPingLabel="最大延迟"; offLabel="关闭"
    groupLabel="分组"; otherLabel="其他"; filtersLabel="筛选"; allProtocols="所有协议"; groupsWord="个分组"; serversWord="台服务器"
    addServerOrSubscription="添加服务器或订阅"; subscriptionLink="订阅链接"; sortDefaultLabel="默认"
    resetFilters="重置"; nothingFound="没有符合筛选条件的服务器"; groupsAndServers="分组和服务器"
    masqueProfileIdLabel="配置文件 ID"; masqueAuthTokenLabel="认证令牌"
    wgMtuLabel="MTU（可选）"; wgDnsLabel="DNS 服务器（用逗号分隔）"
    wgKeepaliveLabel="Persistent keepalive（秒）"; awgHeadersLabel="AmneziaWG 魔术头"
    telemetryEnabled="发送匿名诊断"
    telemetryEnabledDesc="发送应用版本和匿名错误统计，帮助修复问题"
    muxProtocolLabel="多路复用协议"; muxMinStreamsLabel="最小流数"
    muxPadding="多路复用填充"; muxPaddingDesc="为复用流添加填充，使其大小特征更难识别"
    muxBrutal="TCP Brutal"; muxBrutalDesc="固定速率拥塞控制；需要服务端支持并同时设置上下行速度"
    muxBrutalUpLabel="上行 (Mbps)"; muxBrutalDownLabel="下行 (Mbps)"
    outboundSection="出站连接"
    tcpFastOpen="TCP Fast Open"; tcpFastOpenDesc="在 TCP 握手时发送首个数据包"
    tcpMultiPath="Multipath TCP"; tcpMultiPathDesc="为同一连接使用多条网络路径 (MPTCP)"
    udpFragmentLabel="UDP 分片"; udpFragmentDesc="拆分发出的 UDP 数据包以绕过 DPI"
    udpOverTcpLabel="UDP over TCP"; udpOverTcpDesc="将 UDP 封装在 TCP 流中（仅 Shadowsocks）"
    connectTimeoutLabel="连接超时（秒，0 为默认）"
    urlTestIdleTimeoutLabel="空闲超时（分钟，0 为关闭）"
    urlTestInterrupt="切换时中断连接"
    urlTestInterruptDesc="自动选择切换到其他服务器时断开现有连接"
    loggingEnabled="日志记录"
    loggingEnabledDesc="记录应用和内核日志。关闭后不再记录任何日志，设备上也不保留"
    logLevelAll="全部"; logLevelDebug="调试"; logLevelInfo="信息"
    logLevelWarning="警告"; logLevelError="错误"
    loadOlderLogs="加载更早的记录"
    ovpnCredentialsRequired="此配置使用用户名和密码登录。两项都要填写，否则服务器会拒绝连接。"
    ovpnCertificateOnlyHint="仅证书配置：使用客户端证书认证，无需用户名和密码。"
    cameraPermissionTitle="需要相机权限"
    cameraPermissionMessage="扫描二维码需要使用相机。Lumen 仅在扫描器打开时使用它。"
    cameraPermissionBlocked="Lumen 的相机权限已被关闭，无法启动二维码扫描器。请在应用设置中允许相机权限后重试。"
    openAppSettings="打开设置"
    newGroup="新建分组"; groupNameLabel="分组名称"; createAction="创建"
    renameGroup="重命名分组"; deleteGroup="删除分组"
    deleteGroupConfirm="仅删除该分组。其中的服务器会保留并回到「默认」分组。"
    moveToGroup="移动到分组"; groupNoGroup="不属于任何分组"
    providerAnnouncement="公告"; providerChannel="频道"; providerSupport="支持"; providerEmail="邮箱"
    providerWebsite="官网"; providerPremium="会员"
}

private val FA = LumenStrings().apply {
    localeCode = "fa"
    home="خانه"; servers="سرورها"; routing="مسیریابی"; settings="تنظیمات"; logs="گزارش‌ها"
    subscriptions="اشتراک‌ها"; addSubscription="افزودن اشتراک"; hideSystem="پنهان کردن برنامه‌های سیستمی"
    autoSelect="انتخاب خودکار"; clear="پاک کردن"; language="زبان"; systemDefault="پیش‌فرض سیستم"
    connectingStatus="در حال اتصال…"
    connectionError="خطای اتصال"; diagnostics="عیب‌یابی"
    openLogs="باز کردن گزارش‌ها"; preferIpv6="ترجیح IPv6"
    preferIpv6Description="وقتی IPv4 و IPv6 در دسترس هستند از IPv6 استفاده شود"
    blockQuic="مسدود کردن QUIC"; blockQuicDescription="QUIC روی UDP/443 مسدود و از TCP استفاده شود"
    sniffRouteOnly="اسنیف فقط برای مسیریابی"; sniffRouteOnlyDescription="اسنیف فقط برای مسیریابی باشد و مقصد را تغییر ندهد"
    socksPort="پورت SOCKS"; httpPort="پورت HTTP"
    centerConnect="اتصال"; centerConnecting="در حال اتصال…"; centerConnected="متصل شد"; centerError="خطا"
    importFromClipboard="جای‌گذاری از حافظه"; importQrCode="کد QR"; importFromFile="از فایل"; importManually="دستی"
    refreshSubscription="به‌روزرسانی اشتراک"; deleteSubscription="حذف اشتراک"
    autoUpdateOneHour="به‌روزرسانی خودکار - ۱ ساعت"; expiresUnlimited="انقضا: نامحدود"; daysRemaining="روز باقی‌مانده"
    serverCount="سرور"; sortByPing="مرتب‌سازی بر اساس پینگ"; pingGroup="تست پینگ گروه"
    sortBy="مرتب‌سازی بر اساس:"; sortByName="نام"; subscriptionSettings="تنظیمات اشتراک"
    trafficSettings="تنظیمات ترافیک"; appSettings="تنظیمات برنامه"; infoSection="اطلاعات"
    version="نسخه"; community="انجمن"; back="بازگشت"; requestParameters="پارامترهای درخواست"
    updates="به‌روزرسانی‌ها"; updatesDesc="بررسی نسخه‌های Android در GitHub"
    currentVersion="نسخه فعلی"; latestVersion="آخرین نسخه Android"
    checkUpdates="بررسی به‌روزرسانی"; checkingUpdates="در حال بررسی…"
    updateAvailable="نسخه جدید Android موجود است"; upToDate="آخرین نسخه Android نصب است"
    downloadUpdate="دانلود به‌روزرسانی"; updateCheckFailed="بررسی به‌روزرسانی ناموفق بود"
    autoCheckUpdates="بررسی خودکار به‌روزرسانی‌ها"; autoCheckUpdatesDesc="هنگام باز شدن Lumen، حداکثر روزی یک بار GitHub را بررسی کن"
    androidReleaseTag="برچسب نسخه Android"
    directLoad="بارگیری مستقیم"; directLoadDesc="بارگیری اشتراک بدون استفاده از پروکسی"
    sendHwid="ارسال HWID"; sendHwidDesc="ارسال شناسه دستگاه در هدر X-Hwid"
    allowOverrides="اجازه اعمال تنظیمات اشتراک"; allowOverridesDesc="اعمال تنظیمات سازگار MUX، تکه‌تکه‌سازی و مسیریابی"
    subscriptionAutoUpdate="به‌روزرسانی خودکار اشتراک‌ها"; subscriptionAutoUpdateDesc="به‌روزرسانی دوره‌ای پیوندهای اشتراک در پس‌زمینه"
    subscriptionAutoUpdateInterval="فاصله به‌روزرسانی (دقیقه)"
    subscriptionIncludeRegexLabel="فیلتر شمول (regex)"; subscriptionExcludeRegexLabel="فیلتر استثنا (regex)"
    subscriptionUseProxyTun="بارگیری اشتراک‌ها از طریق تونل پروکسی"; subscriptionUseProxyTunDesc="ارسال درخواست‌های اشتراک از طریق تونل VPN فعال"
    subscriptionAllowHttp="اجازه پیوندهای HTTP اشتراک"; subscriptionAllowHttpDesc="اجازه پیوندهای قدیمی رمزنگاری‌نشده؛ توکن اشتراک ممکن است در شبکه قابل مشاهده باشد"
    subscriptionConverter="مبدل اشتراک"; subscriptionConverterDesc="تبدیل پیوندهای اشتراک با استفاده از سرویس مبدل خارجی"
    subscriptionConverterUrlLabel="نشانی URL مبدل"
    subscriptionProfile="پروفایل اشتراک"; proxyDns="دی‌ان‌اس پروکسی"; directDns="دی‌ان‌اس مستقیم"
    autoSelectUrl="آدرس بررسی"; checkInterval="فاصله بررسی (دقیقه)"; toleranceMs="تحمل تاخیر (میلی‌ثانیه)"
    appearance="ظاهر"; theme="پوسته"; domainIpRouting="مسیریابی دامنه / IP"
    appRouting="مسیریابی برنامه‌ها"; geoResourceFiles="فایل‌های منابع جغرافیا"; domainsAndIpDirect="دامنه‌ها و IPهای مستقیم"
    directRulesNotice="آدرس‌های مشخص شده پروکسی را دور می‌زنند. تغییرات در اتصال بعدی اعمال می‌شوند."
    domainsDirectLabel="دامنه‌های مستقیم"; ipCidrDirectLabel="IP / CIDR مستقیم"
    geoSourceLabel="منبع اطلاعات جغرافیایی"; geoNotLoaded="فایل‌ها هنوز دانلود نشده‌اند"
    geoManagedByCore="هنگام استفاده از قانون جغرافیایی، sing-box extended مجموعه‌قوانین باینری دقیق .srs را دانلود و در کش نگه می‌دارد. فایل‌های قدیمی geosite.dat و geoip.dat استفاده نمی‌شوند."
    groupDefault="پیش‌فرض"; importAction="وارد کردن"
    themeSettings="شخصی‌سازی"; done="انجام شد";
    dashboardStyle="سبک داشبورد"; dashboardStyleDefault="پیش‌فرض"; dashboardStyleSlider="لغزش برای اتصال"; dashboardStyleCentered="دکمه وسط"; greenTheme="سبز"; greenThemeDesc="جنگل تاریک با رنگ سبز"
    launcherIcon="نماد برنامه"
    launcherIconDesc="ممکن است نماد هنگام بارگذاری دوباره توسط لانچر برای لحظه‌ای ناپدید و دوباره ظاهر شود و برخی لانچرها آن را به انتهای صفحه اصلی منتقل می‌کنند."
    launcherIconSystem="مطابق سیستم"; launcherIconLight="روشن"; launcherIconDark="تیره"
    routingPresets="قوانین پیش‌فرض"; routingPresetsDesc="مجموعه‌های آماده بر پایه geoip/geosite."
    presetLan="دور زدن شبکه محلی"; presetAds="مسدود کردن تبلیغات"; presetRu="دور زدن روسیه"; presetCn="دور زدن چین"; presetIr="دور زدن ایران"; presetGlobalProxy="پروکسی سراسری"; customRules="قوانین سفارشی"
    deleteAllServers="حذف همه سرورها"; deleteAllServersConfirm="همه سرورها از فهرست حذف می‌شوند. اشتراک‌ها باقی می‌مانند و دوباره قابل به‌روزرسانی هستند."
    lightTheme="روشن"; lightThemeDesc="حالت روشن با رنگ‌های ملایم"; darkTheme="تاریک"; darkThemeDesc="تاریک خالص با رنگ آبی"
    additional="اضافی"; materialYou="Material You"
    materialYouDesc="رنگ‌های پویا برگرفته از تصویر زمینه (اندروید ۱۲ به بالا)"
    materialYouUnavailable="به اندروید ۱۲ یا بالاتر نیاز دارد — این دستگاه پالت انتخابی را نگه می‌دارد"
    rosePineTheme="Rosé Pine"; rosePineThemeDesc="آلویی ملایم با تأکید بنفش زنبقی"
    amoledBlack="مشکی AMOLED"
    amoledBlackDesc="مشکی واقعی #000000 — پیکسل‌های OLED خاموش می‌شوند و باتری کمتر مصرف می‌شود"
    connectionStyleTitle="سبک اتصال"; classicStyle="کلاسیک"; compactStyle="فشرده"
    noServer="سروری انتخاب نشده — برای انتخاب ضربه بزنید"; fastest="سریع‌ترین موجود"
    addNode="افزودن سرور"; searchServers="جستجوی سرورها…"; pingAll="تست همه"
    pinging="در حال تست…"; importClipboard="وارد کردن از حافظه"
    noServers="هنوز سروری نیست. یک سرور یا اشتراک اضافه کنید."
    allGroups="همه سرورها"; manual="دستی"; refresh="به‌روزرسانی"; delete="حذف"
    edit="ویرایش"; auto="خودکار"; never="هرگز"; nodes="سرور"; updated="به‌روزشده"
    nameOptional="نام (اختیاری)"; cancel="لغو"; add="افزودن"
    splitTunneling="تونل تفکیکی"; off="خاموش"; offDescription="همه ترافیک از طریق VPN"
    vpnOnly="VPN فقط برای برنامه‌های انتخابی"; vpnOnlyDescription="فقط برنامه‌های علامت‌خورده از تونل استفاده می‌کنند"
    exclude="حذف برنامه‌های انتخابی"; excludeDescription="برنامه‌های علامت‌خورده تونل را دور می‌زنند"
    appsUsingVpn="برنامه‌های متصل به VPN"; appsBypassingVpn="برنامه‌های خارج از VPN"
    searchApps="جستجوی برنامه‌ها…"; loadingApps="در حال بارگذاری برنامه‌ها…"
    vpnEngine="موتور VPN"; connection="اتصال"; muxDescription="استفاده از یک اتصال برای چند جریان"
    muxConcurrency="همزمانی MUX"; tlsFragmentation="تکه‌تکه‌سازی TLS"
    tlsDescription="تقسیم TLS ClientHello برای عبور از DPI"; fragmentPackets="بسته‌های تکه‌شده"
    fragmentLength="طول تکه"; fragmentDelay="تاخیر تکه (میلی‌ثانیه)"; tunnelMtu="MTU تونل"
    localProxy="پروکسی محلی"; localInbound="ورودی محلی SOCKS/HTTP"
    localInboundDescription="پورت‌های 10808 (SOCKS5) و 10809 (HTTP)"; allowLan="اجازه اتصال از شبکه محلی"
    allowLanDescription="اشتراک پروکسی محلی در شبکه"; behavior="رفتار"
    proxyOnly="فقط پروکسی"; proxyOnlyDesc="از پروکسی محلی بدون مسیریابی ترافیک دستگاه از طریق وی‌پی‌ان استفاده کنید. برنامه‌ها را برای استفاده از پروکسی محلی تنظیم کنید. در اتصال بعدی اعمال می‌شود."
    autoConnect="اتصال خودکار در روشن شدن"; autoConnectDescription="اتصال دوباره پس از راه‌اندازی مجدد"
    speedStats="آمار سرعت"; speedStatsDesc="اندازه‌گیری و پیگیری سرعت ترافیک وی‌پن. برای کاهش مصرف باتری خاموش کنید."
    speedTest="تست سرعت"; testing="در حال تست…"; runSpeedTest="شروع تست"; export="خروجی"
    noLogs="هنوز گزارشی ثبت نشده است."; paste="جای‌گذاری"; copyLink="کپی لینک"
    exportQrCode="خروجی کد QR"; ping="پینگ"; subscriptionProperties="ویژگی‌های اشتراک"
    exportAll="خروجی همه"; exportSelected="خروجی موارد انتخابی"; selected="انتخاب‌شده"
    url="آدرس"; copied="کپی شد"; udpPing="پینگ UDP"; address="آدرس"; action="عملکرد"
    directAction="مستقیم"; proxyAction="پروکسی"; blockAction="مسدود"
    noRulesYet="قانونی برای دامنه یا IP تعریف نشده"; clearAll="پاک کردن همه"
    addOrPaste="+ افزودن یا جای‌گذاری"; swipeOrTapToConnect="برای اتصال بکشید"
    swipeOrTapToDisconnect="برای قطع بکشید"; slideToConnect="برای اتصال بکشید"
    slideToDisconnect="برای قطع بکشید"
    dnsSettings="تنظیمات DNS"; dnsModeSection="حالت DNS"; dnsModeAuto="خودکار"
    dnsModeAndroid="DNS اندروید"; dnsModeSecure="امن"; dnsModeJson="از JSON"
    dnsModeAutoHint="پورت 53 درون VPN گرفته می‌شود و حل‌کننده‌ها طبق قوانین انتخاب می‌شوند."
    dnsModeAndroidHint="حل‌کننده سیستمی اندروید بدون مداخله درون VPN."
    dnsModeSecureHint="DoH/DoT فقط از طریق پروکسی؛ پیش از شروع Private DNS بررسی می‌شود."
    dnsModeJsonHint="DNS از پیکربندی JSON شما خوانده می‌شود."
    dnsCustomJsonLabel="JSON سفارشی DNS (شیء dns)"
    dnsDirectSection="DNS مستقیم"; dnsProxySection="DNS از طریق پروکسی"
    dnsServersLabel="سرورها (هر خط یکی)"; dnsTypeLabel="نوع"; dnsStrategyLabel="استراتژی"
    dnsIpv4Only="فقط IPv4 در VPN"; dnsIpv4OnlyDesc="فیلتر کردن AAAA در DNS پروکسی"
    dnsBehaviorSection="رفتار"; dnsHijack="گرفتن DNS در TUN"
    dnsHijackDesc="اجازه ندهید پرس‌وجوهای DNS از حل‌کننده داخلی خارج شوند"
    dnsFakeIp="Fake DNS"; dnsFakeIpDesc="FakeIP پیش‌فرض خاموش است؛ فقط در صورت نیاز فعال کنید"
    dnsParallel="پرس‌وجوی موازی"; dnsParallelDesc="پرس‌وجوی همزمان از حل‌کننده‌های پشتیبان"
    dnsOptimistic="کش خوشبینانه"; dnsOptimisticDesc="پاسخ قدیمی داده و در پس‌زمینه به‌روز می‌شود"
    dnsGeoCheck="بررسی جغرافیایی DNS"; dnsGeoCheckDesc="انتخاب مستقیم/پروکسی را برای قوانین دامنه حفظ می‌کند"
    dnsHostsSection="Hosts و بازنویسی"; dnsHostsLabel="Hosts: domain=ip"
    dnsOverride="بازنویسی DNS"; dnsOverrideDesc="نام دقیق میزبان ← IPv4 پیش از سایر قوانین"
    dnsHostname="نام میزبان"; dnsIpv4="IPv4"
    vibration="لرزش"; vibrationDesc="بازخورد لمسی هنگام لمس و عملیات"
    pingSettings="تنظیمات پینگ"; pingTypeLabel="نوع تست"; pingTimeoutLabel="مهلت (میلی‌ثانیه)"
    pingConcurrencyLabel="تست‌های همزمان"; pingUrlLabel="آدرس تست"; pingAutoOnOpen="پینگ هنگام باز شدن"
    pingAutoOnOpenDesc="هنگام باز شدن فهرست، سرورها تست شوند"
    pingAutoDeleteUnreachable="حذف سرورهای خراب پس از تست پینگ"; pingAutoDeleteUnreachableDesc="نتایج کامل‌شده تا آستانه حذف می‌شوند؛ تست‌های ناتمام حفظ می‌شوند"
    pingAutoDeleteThresholdLabel="حذف در این مقدار یا کمتر (میلی‌ثانیه)"
    categoryAppearance="ظاهر"; categoryConnection="اتصال"; categoryTunnel="تونل"
    categoryProviders="اشتراک‌ها"; categoryOther="سایر"; perAppProxy="پروکسی براساس برنامه"
    trafficUsed="مصرف‌شده"; trafficTotal="کل"; expiresLabel="انقضا"; unlimited="نامحدود"
    subscriptionInfo="اطلاعات اشتراک"; password="گذرواژه"
    editNode="ویرایش سرور"; close="بستن"; nodeName="نام"; protocolField="پروتکل"
    transportLabel="انتقال"; pathLabel="مسیر"; hostHeaderLabel="هدر Host"; grpcServiceNameLabel="gRPC serviceName"
    securityLabel="امنیت"; sniLabel="SNI"; alpnLabel="ALPN (با کاما جدا شود)"
    utlsFingerprintLabel="اثر انگشت uTLS (chrome، firefox\u2026)"; certificateSha256Label="SHA-256 کلید عمومی گواهی (Base64)"; allowInsecureTlsLabel="اجازه TLS ناامن"
    realityPublicKeyLabel="کلید عمومی Reality (pbk)"; realityShortIdLabel="شناسه کوتاه Reality (sid)"
    uuidLabel="UUID"; flowLabel="Flow"; noneOption="(هیچ‌کدام)"; encryptionMethodLabel="روش رمزنگاری"
    passwordAuthLabel="گذرواژه / احراز هویت"; obfsLabel="Obfs (salamander، اختیاری)"; obfsPasswordLabel="گذرواژه Obfs"
    uuidPasswordLabel="UUID:گذرواژه"; congestionControlLabel="کنترل ازدحام"
    userPasswordOptionalLabel="کاربر:گذرواژه (اختیاری)"; privateKeyLabel="کلید خصوصی"
    peerPublicKeyLabel="کلید عمومی همتا"; wgAddressLabel="آدرس (مثلاً 10.0.0.2/32)"
    presharedKeyLabel="کلید مشترک (اختیاری)"; allowedIpsLabel="IPهای مجاز"
    reservedLabel="Reserved (مثلاً 1,2,3 \u2014 اختیاری)"; awgJunkParamsLabel="پارامترهای زائد AmneziaWG"
    amneziaCompatible="سازگار با Amnezia"; amneziaCompatibleDesc="تبدیل WireGuard به AmneziaWG با پارامترهای پیش‌فرض"
    openvpnConfigLabel="پیکربندی OpenVPN (محتوای .ovpn)"
    autoNodeDescriptionLabel="انتخاب خودکار بهترین سرورها"
    serverLabel="سرور"; portLabel="پورت"; saveAction="ذخیره"
    speedLabel="سرعت"; sessionLabel="نشست"
    showNotification="نمایش اعلان VPN"; showNotificationDesc="نمایش دائمی وضعیت اتصال"
    notificationSpeed="آمار سرعت در اعلان"; notificationSpeedDesc="نمایش سرعت فعلی اتصال"
    autoReconnectNetwork="اتصال مجدد هنگام تغییر شبکه"; autoReconnectNetworkDesc="بازسازی تونل هنگام جابه‌جایی بین وای‌فای و داده همراه"
    validateProxyDataPath="اعتبارسنجی مسیر داده پراکسی"; validateProxyDataPathDesc="آزمایش HTTPS از طریق سرور انتخاب‌شده پیش از فعال‌سازی VPN (راه‌اندازی کندتر می‌شود)"
    disableAmnezia="غیرفعال کردن سازگاری Amnezia"; disableAmneziaDesc="حذف پارامترهای اضافی و استفاده به‌صورت WireGuard معمولی"
    useProxyLabel="استفاده از پروکسی"; proxyServerLabel="سرور پروکسی"; proxyUsernameLabel="نام کاربری پروکسی (اختیاری)"; proxyPasswordLabel="گذرواژه پروکسی (اختیاری)"
    obfsProxyHint="obfsproxy داخل Lumen اجرا می‌شود و برنامه جداگانه‌ای لازم نیست"
    pingAttemptsLabel="تعداد تلاش برای هر سرور"; pingAggregateLabel="نتیجه تلاش‌ها"; pingRetryDelayLabel="فاصله بین تلاش‌ها (میلی‌ثانیه)"
    pingThresholds="رنگ‌بندی تأخیر"; pingGoodLabel="خوب تا (میلی‌ثانیه)"; pingFairLabel="متوسط تا (میلی‌ثانیه)"
    pingUrlPresets="نشانی‌های آماده"; resetToDefaults="بازنشانی به پیش‌فرض"; aggregateMin="بهترین"; aggregateAvg="میانگین"; aggregateMedian="میانه"
    sortByNameDesc="نام (نزولی)"; sortByCountry="کشور"; sortByProtocol="پروتکل"
    groupByCountry="گروه‌بندی بر اساس کشور"; onlyReachable="فقط در دسترس‌ها"; maxPingLabel="بیشترین پینگ"; offLabel="خاموش"
    groupLabel="گروه"; otherLabel="سایر"; filtersLabel="فیلترها"; allProtocols="همه پروتکل‌ها"; groupsWord="گروه"; serversWord="سرور"
    addServerOrSubscription="افزودن سرور یا اشتراک"; subscriptionLink="پیوند اشتراک"; sortDefaultLabel="پیش‌فرض"
    resetFilters="بازنشانی"; nothingFound="موردی مطابق فیلترها پیدا نشد"; groupsAndServers="گروه‌ها و سرورها"
    masqueProfileIdLabel="شناسه پروفایل"; masqueAuthTokenLabel="توکن احراز هویت"
    wgMtuLabel="MTU (اختیاری)"; wgDnsLabel="سرورهای DNS (جدا شده با کاما)"
    wgKeepaliveLabel="Persistent keepalive (ثانیه)"; awgHeadersLabel="سرآیندهای جادویی AmneziaWG"
    telemetryEnabled="ارسال گزارش ناشناس"
    telemetryEnabledDesc="ارسال نسخه برنامه و آمار ناشناس خطاها برای کمک به رفع مشکلات"
    muxProtocolLabel="پروتکل چندتایی (MUX)"; muxMinStreamsLabel="کمینه جریان‌ها"
    muxPadding="پرکردن MUX"; muxPaddingDesc="افزودن داده پرکننده تا الگوی اندازه جریان‌ها سخت‌تر شناسایی شود"
    muxBrutal="TCP Brutal"; muxBrutalDesc="کنترل ازدحام با نرخ ثابت؛ نیازمند پشتیبانی سرور و تنظیم هر دو سرعت"
    muxBrutalUpLabel="آپلود (مگابیت/ثانیه)"; muxBrutalDownLabel="دانلود (مگابیت/ثانیه)"
    outboundSection="اتصال‌های خروجی"
    tcpFastOpen="TCP Fast Open"; tcpFastOpenDesc="ارسال نخستین داده همراه با دست‌دهی TCP"
    tcpMultiPath="Multipath TCP"; tcpMultiPathDesc="استفاده از چند مسیر شبکه برای یک اتصال (MPTCP)"
    udpFragmentLabel="تکه‌تکه‌سازی UDP"; udpFragmentDesc="تقسیم بسته‌های UDP خروجی برای عبور از DPI"
    udpOverTcpLabel="UDP روی TCP"; udpOverTcpDesc="انتقال UDP درون جریان TCP (فقط Shadowsocks)"
    connectTimeoutLabel="مهلت اتصال، ثانیه (۰ = پیش‌فرض)"
    urlTestIdleTimeoutLabel="مهلت بی‌کاری (دقیقه، ۰ = خاموش)"
    urlTestInterrupt="قطع اتصال‌ها هنگام تعویض"
    urlTestInterruptDesc="بستن اتصال‌های موجود وقتی انتخاب خودکار به سرور دیگری می‌رود"
    loggingEnabled="ثبت گزارش"
    loggingEnabledDesc="ثبت گزارش‌های برنامه و هسته. در حالت خاموش هیچ گزارشی ثبت و روی دستگاه نگهداری نمی‌شود"
    logLevelAll="همه"; logLevelDebug="اشکال‌زدایی"; logLevelInfo="اطلاعات"
    logLevelWarning="هشدار"; logLevelError="خطا"
    loadOlderLogs="بارگیری رکوردهای قدیمی‌تر"
    ovpnCredentialsRequired="این پروفایل با نام کاربری و گذرواژه وارد می‌شود. هر دو را پر کنید؛ بدون آن‌ها سرور اتصال را رد می‌کند."
    ovpnCertificateOnlyHint="پروفایل فقط با گواهی: احراز هویت با گواهی کلاینت انجام می‌شود و نام کاربری یا گذرواژه لازم نیست."
    cameraPermissionTitle="دسترسی به دوربین لازم است"
    cameraPermissionMessage="برای اسکن کد QR به دوربین نیاز است. Lumen فقط تا زمانی که اسکنر باز است از آن استفاده می‌کند."
    cameraPermissionBlocked="دسترسی دوربین برای Lumen خاموش است، بنابراین اسکنر کد QR اجرا نمی‌شود. در تنظیمات برنامه دوربین را مجاز کنید و دوباره تلاش کنید."
    openAppSettings="باز کردن تنظیمات"
    newGroup="گروه جدید"; groupNameLabel="نام گروه"; createAction="ایجاد"
    renameGroup="تغییر نام گروه"; deleteGroup="حذف گروه"
    deleteGroupConfirm="فقط گروه حذف می‌شود. سرورهای آن باقی می‌مانند و به «پیش‌فرض» برمی‌گردند."
    moveToGroup="انتقال به گروه"; groupNoGroup="بدون گروه"
    providerAnnouncement="اعلان"; providerChannel="کانال"; providerSupport="پشتیبانی"; providerEmail="ایمیل"
    providerWebsite="وب‌سایت"; providerPremium="ویژه"
}

val LocalStrings = staticCompositionLocalOf { EN }

fun stringsForLanguage(code: String): LumenStrings {
    val normalized = code.lowercase()
    val strings = when (normalized) {
        "ru" -> RU
        "zh" -> ZH
        "fa" -> FA
        else -> EN
    }
    // Update installation was added after the original locale tables. Override the
    // old "download" wording here so every language describes the real action:
    // Android downloads, verifies and opens the system installer.
    when (normalized) {
        "ru" -> {
            strings.downloadUpdate = "Обновить"
            strings.downloadingUpdate = "Загрузка обновления\u2026"
            strings.updateInstallPermissionRequired =
                "Разрешите установку приложений из Lumen и вернитесь назад, чтобы продолжить обновление"
            strings.updateInstallerUnavailable = "Системный установщик приложений недоступен"
        }
        "zh" -> {
            strings.downloadUpdate = "更新"
            strings.downloadingUpdate = "正在下载更新\u2026"
            strings.updateInstallPermissionRequired =
                "请允许 Lumen 安装应用，然后返回以继续更新"
            strings.updateInstallerUnavailable = "Android 系统安装程序不可用"
        }
        "fa" -> {
            strings.downloadUpdate = "به\u200cروزرسانی"
            strings.downloadingUpdate = "در حال دانلود به\u200cروزرسانی\u2026"
            strings.updateInstallPermissionRequired =
                "اجازه نصب برنامه\u200cها از Lumen را بدهید، سپس برای ادامه به\u200cروزرسانی بازگردید"
            strings.updateInstallerUnavailable = "نصب\u200cکننده سیستم Android در دسترس نیست"
        }
        else -> {
            strings.downloadUpdate = "Update"
            strings.downloadingUpdate = "Downloading update\u2026"
            strings.updateInstallPermissionRequired =
                "Allow Lumen to install apps, then return to continue the update"
            strings.updateInstallerUnavailable = "Android's package installer is unavailable"
        }
    }
    return strings
}
